version: '3'

services:

  fizzbuzz:
    build:
      context: .
      dockerfile: build/Dockerfile
    container_name: fizzbuzz_dev
    env_file:
      - ./configs/.env
    ports:
      - 9098:9098
    volumes:
      - ./db:/app/db
    # # To activate if you need data persistance across containers
      #   - "./data:/data"
